language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mingjiefeng/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mingjiefeng/docker-react npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react"
#   env: "Docker-react-env"
#   bucket_name: "elasticbeanstalk-us-west-2-30647"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id:
#     secure: $AWS_ACCESS_KEY #travis environment variable
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY" #travis environment variable
